---

- hosts: all
  become: true

  pre_tasks:
    - name: update Debian/Ubuntu repositories
      apt:
        upgrade: dist
        update_cache: yes
        autoremove: yes
      changed_when: False
      become: yes

    - name: install packages
      become: yes
      package:
        name:
          - ansible
          - neofetch
          - htop
        state: latest

  tasks:
    - name: create ansible user
      tags: always
      user:
        name: ansible
        groups: root
        state: present

    - name: add ssh key for ansible
      tags: always
      authorized_key:
        user: ansible
        key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIL7ZKCfGHSEDKqwD7MuL/8y0G2rxSyFESJwkcm17vcT8 ansible"

    - name: add sudoers file for ansible
      tags: always
      become: yes
      copy:
        src: sudoer_ansible
        dest: /etc/sudoers.d/ansible
        owner: root
        group: root
        mode: 0440

    - name: create user bean
      user:
        name: bean
        group: bean
        state: present
        createhome: yes
        shell: /bin/bash

    - name: add sudoers file for bean
      tags: always
      become: yes
      copy:
        src: sudoer_bean
        dest: /etc/sudoers.d/bean
        owner: root
        group: root
        mode: 0440

    - name: Install acer_bean SSH key
      tags: always
      authorized_key:
        user: bean
        key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKIefOlgTs7w/n/wGGv4LWhOfVwzwmbsQx6VB6/cy/Jo acer_bean"
        state: present

    - name: Ensure devin group exists
      tags: always
      group:
        name: devin
        state: present

    - name: create user devin UID 3000
      tags: always
      user:
        name: devin
        uid: 3000
        group: devin
        createhome: yes
        shell: /bin/bash

    - name: add sudo priveleges file for devin
      tags: always
      become: yes
      copy:
        src: sudoer_devin
        dest: /etc/sudoers.d/devin
        owner: root
        group: root
        mode: 0440

    - name: copy .bashrc file to devin
      tags: always
      copy:
        src: files/bashrc
        dest: /home/devin/.bashrc
        owner: devin
        group: devin
        mode: "0644"
      register: result


    - name: Install devin@acer-chromebook SSH key
      tags: always
      authorized_key:
        user: devin
        key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKFnKQ3jN447peX7LZL5jPiiEvWYm3pNDIUAu4eRtURj devin@acer-chromebook"
        state: present

    - name: Install Rivendell SSH key
      tags: always
      authorized_key:
        user: bean
        key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIx7pxPl9zOUCRwBoo9EfDT9Knx/ssU01FFftP6M21Kj bean@rivendell"
        state: absent 

    - name: Disable root login in sshd_config
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^PermitRootLogin"
        line: "PermitRootLogin no"
        state: present

    - name: Disable password authentication in sshd_config
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication'
        line: 'PasswordAuthentication no'
        state: present

    - name: copy .bashrc file
      copy:
        src: files/bashrc
        dest: /home/bean/.bashrc
        owner: bean
        group: bean
        mode: "0644"
      register: result

  handlers:
    - name: Restart SSH
      service:
        name: ssh
        state: restarted

